# Generated by Django 2.2.7 on 2019-12-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20191203_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='above_ground_sighter',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='color_notes',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='combination_of_primary_and',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='hectare',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='hectare_squirrel_number',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='highlight_fur_color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='other_interactions',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='x',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='y',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
