from django.db import models

class Squirrel(models.Model):
    x = models.FloatField()
    y = models.FloatField()
    unique_squirrel_id = models.CharField(max_length=50,primary_key=True)
    hectare = models.CharField(max_length=50)
    shift = models.CharField(max_length=50)
    date = models.CharField(max_length=50)
    hectare_squirrel_number = models.IntegerField()
    age = models.CharField(max_length=50)
    primary_fur_color = models.CharField(max_length=50)
    highlight_fur_color = models.CharField(max_length=50)
    combination_of_primary_and = models.CharField(max_length=50)
    color_notes = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    above_ground_sighter = models.CharField(max_length=50)
    specific_location = models.CharField(max_length=50)
    running = models.NullBooleanField()
    chasing = models.NullBooleanField()
    climbing = models.NullBooleanField()
    eating = models.NullBooleanField()
    foraging = models.NullBooleanField()
    other_activities = models.CharField(max_length=50)
    kuks = models.NullBooleanField()
    quaas = models.NullBooleanField()
    moans = models.NullBooleanField()
    tail_flags = models.NullBooleanField()
    tail_twitches = models.NullBooleanField()
    approaches = models.NullBooleanField()
    indifferent = models.NullBooleanField()
    runs_from = models.NullBooleanField()
    other_interactions = models.CharField(max_length=50)
    
    def __str__(self):
        return self.unique_squirrel_id
