# Generated by Django 2.2.7 on 2019-12-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='y',
            field=models.FloatField(),
        ),
    ]
