# Generated by Django 2.2.7 on 2019-12-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191201_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='approaches',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='chasing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='eating',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='foraging',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='indifferent',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='kuks',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='moans',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='quaas',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='running',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='runs_from',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_flags',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.NullBooleanField(),
        ),
    ]
